# Generated by Django 5.2.4 on 2025-08-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя валюты")),
                ("code", models.CharField(max_length=3, verbose_name="Код валюты")),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=4,
                        verbose_name="Курс валюты к рублю",
                    ),
                ),
            ],
            options={
                "verbose_name": "Валюта",
                "verbose_name_plural": "Валюты",
            },
        ),
    ]
