# Generated by Django 5.2.4 on 2025-08-05 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="rate",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Курс валюты к рублю",
            ),
        ),
    ]
